version: '3.8'

services:
  # server:
  #   image: server:latest
  #   container_name: server
  #   env_file:
  #     - .env
  #   ports:
  #     - '${PORT}:${PORT}'
  #   depends_on:
  #     - db

  db:
    image: postgres:14
    container_name: db
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres:
    name: db-volume
