version: '3.8'

services:
  db:
    image: postgres:14
    container_name: db
    restart: always
    ports:
      - '5436:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27019:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}

  oidc-server-mock:
    image: ghcr.io/soluto/oidc-server-mock:latest
    container_name: oidc-server-mock
    restart: always
    ports:
      - '4011:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_PATH: /tmp/config/server-options.json
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
      USERS_CONFIGURATION_PATH: /tmp/config/users-config.json
    volumes:
      - ./oidc-server-mock/:/tmp/config:ro

volumes:
  postgres:
    name: db-volume-dev
  mongodb_data:
    name: mongodb-sessions-dev
