version: '3.8'

services:
  server:
    image: server:latest
    container_name: server
    restart: always
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
      - mongodb

  db:
    image: postgres:14
    container_name: db
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}

volumes:
  postgres:
    name: db-volume
  mongodb_data:
    name: mongodb-sessions
